### ISSUE TITLE
Allow excluding Obsolete attributes that should not be decorated with ObsoleteEx

### ISSUE THREAD

**Issue by SeanFeldman** [Fody/Obsolete#13]
There are scenarios when `ObsoleteEx` is not needed and plain `Obsolete` is required to have a "warning" forever (type that is public that cannot be removed, but also should not be used as an example).

Currently Fody generates a warning:
```
1>  Fody: Fody (version 2.1.2.0) Executing
1>MSBUILD : warning : Fody/Obsolete: The member `System.TimeSpan Library.Class::Property()` has an ObsoleteAttribute. You should consider replacing it with an ObsoleteExAttribute.
```

Would be nice to get rid of the warning for types/properties by opting out from Fody inspection.

**Comment by SimonCropp** [comment]
sounds good. send us a PR

**Comment by SeanFeldman** [comment]
The royal "us"? 😃 Will try.

**Comment by SimonCropp** [comment]
this is now on nuget
