### ISSUE TITLE
Fody package reference is broken

### ISSUE THREAD

**Issue by bording** [Fody/Obsolete#20]
I see that you've updated to csproj packaging.

However, currently, the default value for PrivateAssets results in build targets/props and analyzers being excluded from transitive references:

![image](https://user-images.githubusercontent.com/753669/34811118-44a46636-f66d-11e7-878a-427d3cd8fdcb.png)

That means if someone just installs the Obsolete.Fody package, the transitive reference to Fody won't work at all because the targets aren't added to the project.

I'd recommend adding `PrivateAssets="none"` to the [package reference](https://github.com/Fody/Obsolete/blob/master/Obsolete/Obsolete.csproj#L12) to fix this.

**Comment by SimonCropp** [comment]
that results in a build error since the AssemblyToProcess tries to run fody. any suggestions on a workaround
