### ISSUE TITLE
ObsoleteExAttribute should derive from ObsoleteAttribute

### ISSUE THREAD

**Issue by MovGP0** [Fody/Obsolete#7]
Because ```ObsoleteExAttribute``` does not derive from ```ObsoleteAttribute```, Resharper does not provide syntax highlighting support for objects that are marked as ```ObsolteEx```.

**Comment by SimonCropp** [comment]
`ObsoleteAttribute` is sealed. dont see any way this can be fixed???

**Comment by MovGP0** [comment]
I see. Thanks.
